# Generated by Django 4.2.15 on 2026-08-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="method",
            field=models.CharField(
                choices=[
                    ("mada", "Mada"),
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("apple_pay", "Apple Pay"),
                    ("stc_pay", "STC Pay"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
