# Generated by Django 4.2.15 on 2026-08-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0022_add_changes_requested_status"),
        ("payments", "0002_alter_paymenttransaction_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="cars.listingpromotion",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit / reservation"),
                    ("balance", "Final balance"),
                    ("promotion", "Listing promotion"),
                    ("refund", "Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
