# Generated by Django 4.2.15 on 2026-03-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0007_showroom_cover_photo_showroom_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('search_result', 'Search Result'), ('listing_page', 'Listing Page'), ('featured', 'Featured'), ('compare', 'Compare'), ('homepage', 'Homepage'), ('other', 'Other')], default='listing_page', max_length=30)),
                ('dealer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_sent', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_received', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cars.listing')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_status_94f025_idx'), models.Index(fields=['dealer'], name='leads_dealer__87c324_idx'), models.Index(fields=['listing'], name='leads_listing_ab6215_idx'), models.Index(fields=['created_at'], name='leads_created_e6e479_idx')],
            },
        ),
    ]
