# Generated by Django 4.2.15 on 2026-05-19 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCountry',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('flag_emoji', models.CharField(blank=True, default='', max_length=8)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('avg_shipping_cost_sar', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_shipping_days', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source Country',
                'verbose_name_plural': 'Source Countries',
                'ordering': ['display_order', 'name_en'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='source_coun_is_acti_b82552_idx')],
            },
        ),
    ]
