# Generated by Django 4.2.15 on 2026-03-16 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('dealership', 'Dealership'), ('showroom', 'Showroom')], default='individual', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('expected_listings', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dealer_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='dealer_appl_status_32477b_idx'), models.Index(fields=['applicant'], name='dealer_appl_applica_5b6f5f_idx')],
            },
        ),
    ]
