# Generated by Django 4.2.15 on 2026-03-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_alter_auditlog_action_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('status_change', 'Status Change'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('password_changed', 'Password Changed')], max_length=30),
        ),
    ]
