# Generated by Django 4.2.15 on 2026-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0004_phase_3_4_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('status_change', 'Status Change'), ('request_changes', 'Request Changes'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('password_changed', 'Password Changed'), ('otp_login', 'OTP Login')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id', '-timestamp'], name='audit_logs_model_n_a01bd9_idx'),
        ),
    ]
