# Generated by Django 4.2.15 on 2026-08-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0002_change_car_to_listing"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="favorite",
            new_name="favorites_listing_c8e48c_idx",
            old_name="favorites_listing_idx",
        ),
    ]
