# Generated by Django 4.2.15 on 2026-02-21 21:06

from django.db import migrations, models


def map_old_roles_to_new(apps, schema_editor):
    """Update role column with raw SQL so we don't trigger old choice validation."""
    from django.db import connection
    with connection.cursor() as c:
        c.execute("UPDATE users SET role = 'admin' WHERE role = 'ADMIN'")
        c.execute("UPDATE users SET role = 'dealer' WHERE role = 'SELLER'")
        c.execute("UPDATE users SET role = 'user' WHERE role = 'BUYER'")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(map_old_roles_to_new, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
