# Generated by Django 4.2.15 on 2026-03-15 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_bio_user_city_obj_user_show_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('phone_verification', 'Phone Verification'), ('login', 'Login'), ('password_reset', 'Password Reset')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='otp_codes_user_id_2cfe24_idx'), models.Index(fields=['phone'], name='otp_codes_phone_784481_idx'), models.Index(fields=['code'], name='otp_codes_code_42d221_idx'), models.Index(fields=['purpose'], name='otp_codes_purpose_33343b_idx'), models.Index(fields=['expires_at'], name='otp_codes_expires_348c2d_idx')],
            },
        ),
    ]
