# Generated by Django 4.2.15 on 2026-04-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_ban_reason_user_is_banned_user_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
