# Generated by Django 4.2.15 on 2026-04-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_rating_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('importer', 'Importer'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
