# Generated by Django 4.2.15 on 2026-04-08 17:11

from django.db import migrations


def rename_dealer_to_importer(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='dealer').update(role='importer')


def reverse_migrate(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='importer').update(role='dealer')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_dealer_to_importer'),
    ]

    operations = [
        migrations.RunPython(rename_dealer_to_importer, reverse_migrate),
    ]
