# Generated by Django 4.2.15 on 2026-09-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=20),
        ),
    ]
