# Generated by Django 4.2.15 on 2026-04-05 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0018_rename_listing_is_featured_idx_listings_is_feat_01aa9f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveIntegerField(default=5)),
                ('listings_today', models.PositiveIntegerField(default=0)),
                ('last_reset', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('action', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('create_listing', 'Create Listing'), ('submit_lead', 'Submit Lead'), ('submit_report', 'Submit Report')], max_length=20)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='fraud_iplog_user_id_82c15b_idx'), models.Index(fields=['ip_address'], name='fraud_iplog_ip_addr_1cc482_idx'), models.Index(fields=['action'], name='fraud_iplog_action_94ec48_idx'), models.Index(fields=['-created_at'], name='fraud_iplog_created_bcc4f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('duplicate_vin', 'Duplicate VIN'), ('suspicious_price', 'Suspicious Price'), ('excessive_listings', 'Excessive Listings'), ('rapid_posting', 'Rapid Posting'), ('banned_keywords', 'Banned Keywords'), ('ip_abuse', 'IP Abuse'), ('fake_images', 'Fake Images'), ('price_manipulation', 'Price Manipulation')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('auto_detected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='cars.listing')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_flags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['listing'], name='fraud_fraud_listing_300750_idx'), models.Index(fields=['user'], name='fraud_fraud_user_id_549618_idx'), models.Index(fields=['flag_type'], name='fraud_fraud_flag_ty_3b30b5_idx'), models.Index(fields=['severity'], name='fraud_fraud_severit_7d43ae_idx'), models.Index(fields=['is_resolved'], name='fraud_fraud_is_reso_1c9802_idx'), models.Index(fields=['-created_at'], name='fraud_fraud_created_5a7e99_idx')],
            },
        ),
    ]
