# Generated by Django 4.2.15 on 2026-04-21 10:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accuracy_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 rating for information accuracy', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 rating for importer communication', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='delivery_speed_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 rating for delivery speed', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.importorder'),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 overall satisfaction rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('buyer_to_seller', 'Buyer to Seller'), ('seller_to_buyer', 'Seller to Buyer'), ('showroom', 'Showroom Review'), ('workshop', 'Workshop Review'), ('importer_order', 'Importer Order Review')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order'], name='reviews_rev_order_i_a8ba91_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('reviewer', 'order'), name='unique_review_per_order'),
        ),
    ]
