# Generated by Django 4.2.15 on 2026-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contains_contact_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
