# Generated by Django 4.2.15 on 2026-01-23 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=20)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('CVT', 'CVT')], max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('CERTIFIED_PRE_OWNED', 'Certified Pre-owned')], default='USED', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('PENDING', 'Pending'), ('DRAFT', 'Draft')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'db_table': 'car_images',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['car'], name='car_images_car_id_c57a3e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make'], name='cars_make_2a151c_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['model'], name='cars_model_af2c08_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='cars_price_bd5046_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='cars_year_6f2c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status'], name='cars_status_5ca548_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['seller'], name='cars_seller__d68c88_idx'),
        ),
    ]
