# Generated by Django 4.2.15 on 2026-02-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_listing_showroom_workshop_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['make'], name='listings_make_fa5a57_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['model'], name='listings_model_e63277_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_price_e6fc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['year'], name='listings_year_cbd902_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_city_67a231_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listings_status_c3eaec_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['owner'], name='listings_owner_i_d70a22_idx'),
        ),
    ]
