# Generated by Django 4.2.15 on 2026-03-02 20:27

import cars.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0005_listing_soft_delete_and_approval_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[cars.models.validate_vin]),
        ),
        migrations.AddField(
            model_name='workshop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to=settings.AUTH_USER_MODEL),
        ),
    ]
