# Generated by Django 4.2.15 on 2026-03-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_showroom_cover_photo_showroom_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='accident_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='accident_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('truck', 'Truck'), ('van', 'Van'), ('wagon', 'Wagon'), ('convertible', 'Convertible'), ('crossover', 'Crossover'), ('pickup', 'Pickup'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='color_interior',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('cpo', 'Certified Pre-Owned')], max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='customs_cleared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='cylinders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='doors',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-Wheel Drive'), ('rwd', 'Rear-Wheel Drive'), ('awd', 'All-Wheel Drive'), ('4wd', '4-Wheel Drive')], max_length=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG'), ('lpg', 'LPG')], max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='imported_from',
            field=models.CharField(blank=True, choices=[('local', 'Saudi (Local)'), ('gcc', 'GCC Countries'), ('american', 'American Import'), ('european', 'European Import'), ('korean', 'Korean Import'), ('japanese', 'Japanese Import'), ('other', 'Other')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='seats',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT')], max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='warranty_remaining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['body_type'], name='listings_body_ty_da4aff_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['drive_type'], name='listings_drive_t_5efc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['fuel_type'], name='listings_fuel_ty_70243e_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['transmission'], name='listings_transmi_ae21b9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['imported_from'], name='listings_importe_7368a1_idx'),
        ),
    ]
