# Generated by Django 4.2.15 on 2026-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_saved_search_recently_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='color_ar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='color_interior_ar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='make_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='model_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
