# Generated by Django 4.2.15 on 2026-03-10 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0011_listing_arabic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='unique_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(choices=[('search', 'Search'), ('direct', 'Direct'), ('featured', 'Featured'), ('compare', 'Compare'), ('shared', 'Shared'), ('other', 'Other')], default='direct', max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='cars.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'view_logs',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['listing'], name='view_logs_listing_dc637f_idx'), models.Index(fields=['user'], name='view_logs_user_id_62a69f_idx'), models.Index(fields=['ip_address'], name='view_logs_ip_addr_5c029c_idx'), models.Index(fields=['viewed_at'], name='view_logs_viewed__991027_idx')],
            },
        ),
    ]
