# Generated by Django 4.2.15 on 2026-03-16 09:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0013_listing_admin_notes_listing_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('address_ar', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'showroom_branches',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField(blank=True, default='', max_length=1000)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'showroom_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'showroom_working_hours',
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='showroom',
            name='active_listings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showroom',
            name='address_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='showroom',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='showroom',
            name='commercial_registration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='showroom',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='showroom',
            name='description_ar',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='showroom',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='showroom',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showroom',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='showroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='showroom',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showroom',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='showroom',
            name='snapchat',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='showroom',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='showroom',
            name='tiktok',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='showroom',
            name='total_listings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showroom',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showroom',
            name='total_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showroom',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='showroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='showroom',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showroom',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='showroom',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='showroom',
            index=models.Index(fields=['is_active'], name='showrooms_is_acti_d10887_idx'),
        ),
        migrations.AddIndex(
            model_name='showroom',
            index=models.Index(fields=['is_verified'], name='showrooms_is_veri_31a64e_idx'),
        ),
        migrations.AddIndex(
            model_name='showroom',
            index=models.Index(fields=['city_obj'], name='showrooms_city_ob_676cef_idx'),
        ),
        migrations.AddField(
            model_name='showroomworkinghours',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='cars.showroom'),
        ),
        migrations.AddField(
            model_name='showroomreview',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.showroom'),
        ),
        migrations.AddField(
            model_name='showroomreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showroombranch',
            name='city_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_branches', to='locations.city'),
        ),
        migrations.AddField(
            model_name='showroombranch',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='cars.showroom'),
        ),
        migrations.AlterUniqueTogether(
            name='showroomworkinghours',
            unique_together={('showroom', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='showroomreview',
            unique_together={('showroom', 'user')},
        ),
    ]
