# Generated by Django 4.2.15 on 2026-03-17 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0014_showroombranch_showroomreview_showroomworkinghours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField(blank=True, default='', max_length=1000)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workshop_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('description_ar', models.TextField(blank=True, default='', max_length=500)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('bodywork', 'Body Work'), ('electrical', 'Electrical'), ('ac', 'AC & Cooling'), ('tires', 'Tires & Wheels'), ('engine', 'Engine'), ('transmission', 'Transmission'), ('diagnostics', 'Diagnostics'), ('detailing', 'Detailing'), ('other', 'Other')], default='other', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed'), ('starting_from', 'Starting From'), ('hourly', 'Hourly'), ('contact', 'Contact for Price')], default='fixed', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'workshop_services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'workshop_working_hours',
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='workshop',
            name='address_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='workshop',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='workshop',
            name='commercial_registration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='workshop',
            name='description_ar',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='workshop',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='workshop',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workshop',
            name='snapchat',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workshop',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workshop',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workshop',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['is_active'], name='workshops_is_acti_747917_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['is_verified'], name='workshops_is_veri_962a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['city_obj'], name='workshops_city_ob_630875_idx'),
        ),
        migrations.AddField(
            model_name='workshopworkinghours',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='cars.workshop'),
        ),
        migrations.AddField(
            model_name='workshopservice',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='cars.workshop'),
        ),
        migrations.AddField(
            model_name='workshopreview',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='cars.workshopservice'),
        ),
        migrations.AddField(
            model_name='workshopreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshopreview',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='workshopworkinghours',
            unique_together={('workshop', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='workshopreview',
            unique_together={('workshop', 'user')},
        ),
    ]
