# Generated by Django 4.2.15 on 2026-04-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_promotion_package_listing_promotion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_is_feat_01aa9f_idx',
            old_name='listing_is_featured_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_is_top__d23ee7_idx',
            old_name='listing_is_top_search_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_promoti_80dd69_idx',
            old_name='listing_promo_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='listingpromotion',
            new_name='listing_pro_listing_5ed08e_idx',
            old_name='lp_listing_idx',
        ),
        migrations.RenameIndex(
            model_name='listingpromotion',
            new_name='listing_pro_dealer__6d86c4_idx',
            old_name='lp_dealer_idx',
        ),
        migrations.RenameIndex(
            model_name='listingpromotion',
            new_name='listing_pro_status_55f2a8_idx',
            old_name='lp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='listingpromotion',
            new_name='listing_pro_expires_f00234_idx',
            old_name='lp_expires_at_idx',
        ),
        migrations.RenameIndex(
            model_name='listingpromotion',
            new_name='listing_pro_package_c37cef_idx',
            old_name='lp_package_idx',
        ),
    ]
