# Generated by Django 4.2.15 on 2026-04-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_rename_listing_is_featured_idx_listings_is_feat_01aa9f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='actual_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='auction_lot_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='auction_source',
            field=models.CharField(blank=True, choices=[('copart', 'Copart'), ('iaai', 'IAAI'), ('uss_japan', 'USS Japan'), ('manheim', 'Manheim'), ('private', 'Private Sale'), ('dealer', 'Dealer'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='autocheck_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='bill_of_lading_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='carfax_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='conformity_certificate_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='container_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='customs_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='customs_declaration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='customs_duty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='damage_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='emissions_compliant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='estimated_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='final_price_sar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='gcc_specs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_flood_damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_frame_damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_salvage_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='import_status',
            field=models.CharField(blank=True, choices=[('sourcing', 'Sourcing'), ('available', 'Available'), ('reserved', 'Reserved'), ('purchased', 'Purchased'), ('preparing', 'Preparing'), ('shipping', 'Shipping'), ('at_port', 'At Port'), ('in_customs', 'In Customs'), ('customs_cleared', 'Customs Cleared'), ('inspection', 'Inspection'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='available', max_length=25),
        ),
        migrations.AddField(
            model_name='listing',
            name='inspection_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='odometer_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='original_listing_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='port_of_entry',
            field=models.CharField(blank=True, choices=[('jeddah_islamic_port', 'Jeddah Islamic Port'), ('king_abdulaziz_port_dammam', 'King Abdulaziz Port (Dammam)'), ('jubail_port', 'Jubail Commercial Port')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='port_of_origin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_line',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_country',
            field=models.CharField(blank=True, choices=[('usa', 'USA'), ('uae', 'UAE'), ('japan', 'Japan'), ('korea', 'South Korea'), ('qatar', 'Qatar'), ('europe', 'Europe'), ('canada', 'Canada'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('aed', 'AED'), ('jpy', 'JPY'), ('krw', 'KRW'), ('eur', 'EUR'), ('cad', 'CAD'), ('gbp', 'GBP'), ('qar', 'QAR')], default='usd', max_length=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='spec_origin',
            field=models.CharField(blank=True, choices=[('gcc', 'GCC'), ('american', 'American'), ('european', 'European'), ('japanese', 'Japanese'), ('korean', 'Korean')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_landed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='transportation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_inspection_result',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_required', 'Not Required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='vessel_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
