# Generated by Django 4.2.15 on 2026-05-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reservation'),
        ('cars', '0019_add_import_fields_to_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.reservation'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
