# Generated by Django 4.2.15 on 2026-05-19 11:12

from django.db import migrations, models
import django.db.models.deletion


def populate_source_country_fk(apps, schema_editor):
    Listing = apps.get_model("cars", "Listing")
    SourceCountry = apps.get_model("source_countries", "SourceCountry")
    countries = {c.code: c for c in SourceCountry.objects.all()}
    for listing in Listing.objects.all().iterator(chunk_size=500):
        code = (listing.source_country or "").strip().lower()
        country = countries.get(code) or countries.get("other")
        if country:
            listing.source_country_obj_id = country.code
            listing.save(update_fields=["source_country_obj"])


def reverse_populate(apps, schema_editor):
    Listing = apps.get_model("cars", "Listing")
    Listing.objects.all().update(source_country_obj=None)


class Migration(migrations.Migration):

    dependencies = [
        ('source_countries', '0002_seed_initial_countries'),
        ('cars', '0020_listing_current_reservation_listing_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='source_country_obj',
            field=models.ForeignKey(blank=True, help_text='FK replacement for source_country CharField (two-phase migration).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='source_countries.sourcecountry'),
        ),
        migrations.RunPython(populate_source_country_fk, reverse_populate),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['source_country_obj', 'import_status'], name='listings_source__f0bb75_idx'),
        ),
    ]
