# Generated by Django 4.2.15 on 2026-09-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_add_changes_requested_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fx_rate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='fx_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='margin_sar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
