# Generated by Django 4.2.15 on 2026-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_listing_submitted_at_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
