# Generated by Django 4.2.15 on 2026-04-05 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0018_rename_listing_is_featured_idx_listings_is_feat_01aa9f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('listing', 'Listing'), ('user', 'User'), ('showroom', 'Showroom'), ('workshop', 'Workshop'), ('review', 'Review'), ('message', 'Message')], max_length=20)),
                ('reason', models.CharField(choices=[('fake_listing', 'Fake Listing'), ('wrong_price', 'Wrong/Misleading Price'), ('wrong_info', 'Incorrect Information'), ('duplicate', 'Duplicate Listing'), ('scam', 'Scam/Fraud'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('stolen_photos', 'Stolen Photos'), ('sold_vehicle', 'Vehicle Already Sold'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='reports/evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('warning_issued', 'Warning Issued'), ('listing_removed', 'Listing Removed'), ('listing_suspended', 'Listing Suspended'), ('user_warned', 'User Warned'), ('user_suspended', 'User Suspended'), ('user_banned', 'User Banned')], default='none', max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cars.listing')),
                ('reported_showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cars.showroom')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reported_workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cars.workshop')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('warning', 'Warning'), ('suspension', 'Temporary Suspension'), ('ban', 'Permanent Ban'), ('lifted', 'Restriction Lifted')], max_length=20)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_issued', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='moderation__reporte_6f6e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='moderation__status_3fc7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['priority'], name='moderation__priorit_c01053_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='moderation__report__d0024a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='moderation__created_7bb7e8_idx'),
        ),
    ]
