# Generated by Django 4.2.15 on 2026-04-08 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('commercial_registration', models.CharField(blank=True, default='', max_length=50)),
                ('customs_broker_license', models.CharField(blank=True, default='', max_length=100)),
                ('import_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('source_countries', models.JSONField(blank=True, default=list)),
                ('years_in_business', models.PositiveIntegerField(default=0)),
                ('total_cars_imported', models.PositiveIntegerField(default=0)),
                ('average_delivery_days', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('logo', models.CharField(blank=True, default='', max_length=500)),
                ('cover_photo', models.CharField(blank=True, default='', max_length=500)),
                ('instagram', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('snapchat', models.CharField(blank=True, default='', max_length=100)),
                ('tiktok', models.URLField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('address_ar', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='importer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
