# Generated by Django 4.2.15 on 2026-04-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerprofile',
            name='avg_accuracy_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='avg_communication_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='avg_delivery_speed_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='avg_overall_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
