# Generated by Django 4.2.15 on 2026-05-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importers', '0002_importerprofile_avg_accuracy_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerprofile',
            name='cr_document',
            field=models.FileField(blank=True, null=True, upload_to='cr_documents/'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='cr_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='cr_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='cr_last_confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='cr_reactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='cr_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='cr_verification_status',
            field=models.CharField(choices=[('pending_initial', 'Pending Initial Verification'), ('verified', 'Verified & Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('suspended', 'Suspended (CR Expired)'), ('renewal_under_review', 'Renewal Under Review')], default='pending_initial', max_length=30),
        ),
        migrations.CreateModel(
            name='CRVerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('initial_submission', 'Initial CR Submitted'), ('initial_verified', 'Initial CR Verified'), ('renewal_submitted', 'Renewal Submitted'), ('renewal_approved', 'Renewal Approved'), ('renewal_rejected', 'Renewal Rejected'), ('auto_suspended', 'Auto-Suspended (Expired)'), ('manual_suspended', 'Manually Suspended'), ('reactivated', 'Reactivated'), ('reminder_sent_60', '60-Day Reminder Sent'), ('reminder_sent_30', '30-Day Reminder Sent'), ('reminder_sent_7', '7-Day Reminder Sent'), ('reminder_sent_expired', 'Expiry-Day Reminder Sent')], max_length=30)),
                ('old_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('cr_expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('document_uploaded', models.FileField(blank=True, null=True, upload_to='cr_renewals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_history', to='importers.importerprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
