# Generated by Django 4.2.15 on 2026-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_seed_exchange_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='last_api_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='last_api_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='previous_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_to_sar',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
