# Generated by Django 4.2.15 on 2026-09-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
