# Generated by Django 4.2.15 on 2026-03-17 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_workshopreview_workshopservice_workshopworkinghours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vehicle_plate', models.CharField(blank=True, default='', max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='cars.workshopservice')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='cars.workshop')),
            ],
            options={
                'db_table': 'service_bookings',
                'ordering': ['-booking_date', '-booking_time'],
                'indexes': [models.Index(fields=['workshop'], name='service_boo_worksho_2a4f1f_idx'), models.Index(fields=['customer'], name='service_boo_custome_1f1a2a_idx'), models.Index(fields=['status'], name='service_boo_status_43b712_idx'), models.Index(fields=['booking_date'], name='service_boo_booking_5a044f_idx')],
            },
        ),
    ]
