# Generated by Django 4.2.15 on 2026-04-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0019_add_import_fields_to_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deposit_requested', 'Deposit Requested'), ('deposit_paid', 'Deposit Paid'), ('confirmed', 'Confirmed'), ('sourcing', 'Sourcing'), ('purchased', 'Purchased'), ('preparing_shipment', 'Preparing Shipment'), ('shipped', 'Shipped'), ('arrived_port', 'Arrived at Port'), ('in_customs', 'In Customs'), ('customs_cleared', 'Customs Cleared'), ('inspection', 'Inspection'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=30)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('buyer_notes', models.TextField(blank=True, default='')),
                ('importer_notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_cancelled', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_orders', to='cars.listing')),
                ('importer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_importer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('bill_of_lading', 'Bill of Lading'), ('customs_declaration', 'Customs Declaration'), ('customs_clearance', 'Customs Clearance Certificate'), ('inspection_report', 'Inspection Report'), ('conformity_cert', 'Conformity Certificate'), ('title_deed', 'Title Deed'), ('delivery_receipt', 'Delivery Receipt'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='orders/documents/')),
                ('is_buyer_visible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.importorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_order_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('deposit_requested', 'Deposit Requested'), ('deposit_paid', 'Deposit Paid'), ('order_confirmed', 'Order Confirmed'), ('sourcing_started', 'Sourcing Started'), ('car_purchased', 'Car Purchased'), ('preparing_shipment', 'Preparing Shipment'), ('shipped', 'Shipped'), ('arrived_port', 'Arrived at Port'), ('customs_started', 'Customs Started'), ('customs_cleared', 'Customs Cleared'), ('inspection_scheduled', 'Inspection Scheduled'), ('inspection_passed', 'Inspection Passed'), ('inspection_failed', 'Inspection Failed'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('note', 'Note'), ('document_uploaded', 'Document Uploaded'), ('status_update', 'Status Update')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='orders.importorder')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='importorder',
            index=models.Index(fields=['status'], name='orders_impo_status_426ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='importorder',
            index=models.Index(fields=['buyer'], name='orders_impo_buyer_i_5e936a_idx'),
        ),
        migrations.AddIndex(
            model_name='importorder',
            index=models.Index(fields=['importer'], name='orders_impo_importe_66463e_idx'),
        ),
        migrations.AddIndex(
            model_name='importorder',
            index=models.Index(fields=['order_number'], name='orders_impo_order_n_012e37_idx'),
        ),
    ]
