# Generated by Django 4.2.15 on 2026-05-16 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0019_add_import_fields_to_listing'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('cancelled_by_buyer', 'Cancelled by Buyer'), ('cancelled_by_importer', 'Cancelled by Importer'), ('converted_to_order', 'Converted to Order'), ('expired', 'Expired')], default='pending_payment', max_length=30)),
                ('platform_fee_sar', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mada', 'Mada'), ('apple_pay', 'Apple Pay'), ('stc_pay', 'STC Pay'), ('visa_mastercard', 'Visa / Mastercard')], default='mada', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('buyer_notes', models.TextField(blank=True, default='')),
                ('importer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='cars.listing')),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_reservation', to='orders.importorder')),
                ('importer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_as_importer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_rese_status_c4dc34_idx'), models.Index(fields=['buyer'], name='orders_rese_buyer_i_5978f1_idx'), models.Index(fields=['importer'], name='orders_rese_importe_6ec0dd_idx'), models.Index(fields=['car'], name='orders_rese_car_id_56de74_idx'), models.Index(fields=['reservation_number'], name='orders_rese_reserva_572178_idx')],
            },
        ),
    ]
