# Generated by Django 4.2.15 on 2026-05-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_review', 'Pending Importer Review'), ('active', 'Active (deprecated)'), ('cancelled_by_buyer', 'Cancelled by Buyer'), ('cancelled_by_importer', 'Cancelled by Importer'), ('converted_to_order', 'Converted to Order'), ('expired', 'Expired')], default='pending_payment', max_length=30),
        ),
    ]
