# Generated by Django 4.2.15 on 2026-08-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importtimeline",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order_placed", "Order Placed"),
                    ("deposit_requested", "Deposit Requested"),
                    ("deposit_paid", "Deposit Paid"),
                    ("order_confirmed", "Order Confirmed"),
                    ("sourcing_started", "Sourcing Started"),
                    ("car_purchased", "Car Purchased"),
                    ("preparing_shipment", "Preparing Shipment"),
                    ("shipped", "Shipped"),
                    ("arrived_port", "Arrived at Port"),
                    ("customs_started", "Customs Started"),
                    ("customs_cleared", "Customs Cleared"),
                    ("inspection_scheduled", "Inspection Scheduled"),
                    ("inspection_passed", "Inspection Passed"),
                    ("inspection_failed", "Inspection Failed"),
                    ("ready_for_pickup", "Ready for Pickup"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("disputed", "Disputed"),
                    ("note", "Note"),
                    ("document_uploaded", "Document Uploaded"),
                    ("status_update", "Status Update"),
                    ("payment", "Payment"),
                ],
                max_length=30,
            ),
        ),
    ]
