# Generated by Django 4.2.15 on 2026-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_importtimeline_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car_import_status_before',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
