# Generated by Django 4.2.15 on 2026-09-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_backfill_reservation_locks'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='importorder',
            name='shipment_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        # Django applies `default=''` in Python and drops the DB default once
        # existing rows are backfilled, which leaves two NOT NULL columns that
        # only this branch's code knows to populate. On a shared database that
        # everyone checks out different branches against, an INSERT from code
        # written before these fields then fails outright — which is exactly
        # how auditlog.user_agent took out every audited write. Keeping a
        # server-side default costs nothing and makes the schema tolerant of
        # code both older and newer than itself.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE orders_importorder ALTER COLUMN shipment_number SET DEFAULT ''",
                "ALTER TABLE orders_importorder ALTER COLUMN carrier SET DEFAULT ''",
            ],
            reverse_sql=[
                "ALTER TABLE orders_importorder ALTER COLUMN shipment_number DROP DEFAULT",
                "ALTER TABLE orders_importorder ALTER COLUMN carrier DROP DEFAULT",
            ],
        ),
    ]
