# Generated by Django 4.2.15 on 2026-03-10 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
        ('bookings', '0001_initial_appointment'),
        ('cars', '0013_listing_admin_notes_listing_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('new_lead', 'New Lead'), ('lead_status_changed', 'Lead Status Changed'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_cancelled', 'Appointment Cancelled'), ('price_drop', 'Price Drop'), ('listing_expiring', 'Listing Expiring'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.appointment')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='leads.lead')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cars.listing')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='notificatio_recipie_1dd18d_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
