# Generated by Django 4.2.15 on 2026-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('new_lead', 'New Lead'), ('lead_status_changed', 'Lead Status Changed'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_cancelled', 'Appointment Cancelled'), ('price_drop', 'Price Drop'), ('listing_expiring', 'Listing Expiring'), ('system', 'System Notification'), ('new_message', 'New Message'), ('conversation_started', 'Conversation Started'), ('user_blocked', 'User Blocked')], max_length=50),
        ),
    ]
