# Generated by Django 4.2.15 on 2026-03-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_approved', models.BooleanField(default=True)),
                ('listing_rejected', models.BooleanField(default=True)),
                ('new_lead', models.BooleanField(default=True)),
                ('lead_status_changed', models.BooleanField(default=True)),
                ('new_message', models.BooleanField(default=True)),
                ('conversation_started', models.BooleanField(default=True)),
                ('appointment_confirmed', models.BooleanField(default=True)),
                ('appointment_rejected', models.BooleanField(default=True)),
                ('appointment_cancelled', models.BooleanField(default=True)),
                ('price_drop', models.BooleanField(default=True)),
                ('listing_expiring', models.BooleanField(default=True)),
                ('system', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
