# Generated by Django 4.2.15 on 2026-04-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='order_updates_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='order_updates_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='order_updates_sms',
            field=models.BooleanField(default=True),
        ),
    ]
